### ISSUE TITLE
[ETL] Incorrect table name used for undoing exits and cancels

### ISSUE THREAD

**Issue by mahalakshme** [avniproject/avni-etl#112]
### Issue:
```
org.springframework.jdbc.BadSqlGrammarException: StatementCallback; bad SQL grammar [delete from "poweratuat"."indivi_exit_compensation_in_case_exit"
using "poweratuat"."indivi_exit_compensation_in_case"
where "poweratuat"."indivi_exit_compensation_in_case_exit".id = "poweratuat"."indivi_exit_compensation_in_case".id
and "poweratuat"."indivi_exit_compensation_in_case".program_exit_date_time is null;]
at org.springframework.jdbc.support.SQLStateSQLExceptionTranslator.doTranslate(SQLStateSQLExceptionTranslator.java:99)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:70)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:79)
at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1538)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:393)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:431)
```

### Tech analysis:
- The program enrolment table name is not always a substring of program exit table name like coded [here](https://github.com/avniproject/avni-etl/blob/eb2f267b53d28394b6abf9d946bbdf431387363e/src/main/java/org/avniproject/etl/repository/sync/CleanEnrolmentExitTableAction.java#L37)
- In power org, exit table is truncated table name, and enrolment table is full name without any truncation.
- Similar case for encounter cancel table names like coded [here](https://github.com/avniproject/avni-etl/issues/75)

### AC:
- The ETLs of power and poweratuat in prerelease should pass after the fix
- Create general encounter type with name 'maternity benefit claims documentationaaaaaaaaaaaa' for subject type 'Individual' and check for the case in [this](https://github.com/avniproject/avni-etl/issues/75) card. Applicable for program encounter as well.
- [This](https://github.com/avniproject/avni-etl/issues/62) and [this](https://github.com/avniproject/avni-etl/issues/75) cards AC should continue to work as expected.

### Questions:
exit and cancel suffixes added at two places when truncated. - just by searching for exit we can find the usage

### Test suggestions
Good to test with few orgs which has exit table issue(power org has this) and general encounter/program encounter issue and normal case as well is my opinion.

**Comment by himeshr** [comment]
Caused an urgent issue for Shelter.. raised as [ticket](https://avni.freshdesk.com/a/tickets/4963)

**Comment by himeshr** [comment]
Since the issue is encountered after recent data-fix in prod env DB, this can currently only be tested on local using dump.
Marking it Tech-qa.

**Comment by himeshr** [comment]
Successfull completed ETL schema run for Shelter org dump on local.

**Comment by mahalakshme** [comment]
tested with power - enrolment -> exit -> undo exit
shelter for program encounter  -> cancel -> undo cancel by syncing with details from different mobile
both above in tables where exit/cancel table names are truncated and original tables whose names not truncated.
