### ISSUE TITLE
Optimize ETL Jobs performance and resource consumption

### ISSUE THREAD

**Issue by himeshr** [avniproject/avni-etl#20]
Optimize ETL Jobs performance and resource consumption

1. Minimize long-running queries impact : Evaluate Query plans to optimise the SQL queries used in ETL jobs.
2. Optimize scheduling for various organizations : We should provide ways to specify different frequency of ETL job trigger for each specific organisation. This would help address performance concerns at the same time satisfying Customer needs, that vary across different organizations.
3. Distribute load over larger period of time: Depends on above mentioned ability to individually trigger ETL jobs for each organisation, so that we space out the jobs with sleep-time interleaved rather than triggering ETL job for all orgs at once.

**Comment by vinayvenu** [comment]
@himeshr can you provide more details on this card?
