### ISSUE TITLE
Secondary table for repeatable question groups

### ISSUE THREAD

**Issue by vindeolal** [avniproject/avni-etl#22]
Store all the group form element observations in a separate table. This will be essential if we are to run reports for grouped form elements. 

With more implementations using group (especially repeated groups) in their implementation, this becomes important to implement. 

Table name - <parent_table>_<question_group_concept_name>

**Comment by arjunk** [comment]
@vinayvenu @vindeolal more details are required on this story

**Comment by petmongrels** [comment]
Commits
- c270b03e52906c2e42cdd8f286dd5a9368157157
- 7d726f80033a328d219a677c319aa8ff051319ff
- 995b680e39c3240e5efd1bbf72e8486f3cd4d2e5
- 60eb5fe54acd5ab10e3550735117bed720e7907f
- 8434e55d795e3c681390f8e5d33c2e3fca72a7b6
- e6aea9e508416fa1b264da7e336bb7259f592500
- e30a626f249b12556aeb6d700b5b8736a4f50ac1
- 0ec2686baab156fcb3e8bcdb5e8cdc5224228573
- 25717070f6a21bdb3afb88555cfc3dfc1bce2098
- a32870a4a6c7a3c44570a85dd24a1d1a45537633

**Comment by vinayvenu** [comment]
This might not work when there is modification of a row since we have a SerialId column defined, and the DuplicateRowDeleteAction identifies duplicates using the id. For example, on the subject_type columns, the id is the same as the id on the individual table, so duplicates can be eliminated.
