### ISSUE TITLE
ETL does not migrate data for groups

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#23]
### To Reproduce
- Set up ETL for a organisation with a group subject type
- Run ETL for the organisation
- See that the table is created, but there are no rows in there. 

Freshdesk ticket - https://avni.freshdesk.com/a/tickets/1987

**Comment by vinayvenu** [comment]
To fix this for an existing table, you need to first remove the sync status for that table. 
eg: 
```delete from entity_sync_status where table_metadata_id = (select id from table_metadata where name = 'slumrim_registration');
```

**Comment by vindeolal** [comment]
Deployed to prod. Deleted the records from entity_sync_status and resynced the data. Data is visible on slumrim_registration table.
