### ISSUE TITLE
Timezone problems for date concepts

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#25]
Date observations are stored in the format "2022-01-01 18:30:00.000" in the observations jsonb. This gets converted to 2022-01-01 in ETL (ideally should have been 2022-01-02 because it is based on IST). 

### Solution
- Move all dates to IST date. 
- Recreate ETL data in prod so that dates show up correctly

### Acceptance criteria
- A date recorded as "2022-01-01" on the avni-client should show up as "2022-01-01" on ETL reports as well. 

https://avni.freshdesk.com/a/tickets/2056

**Comment by vindeolal** [comment]
Tried changing the current date parsing like below
`SELECT ('2022-01-01 18:30:00.000'::timestamptz AT time zone 'asia/kolkata')::date;`
This works fine when run from IDE but somehow is not working when the job executes it.
