### ISSUE TITLE
Media listing API

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#32]
### Story
- avni-etl will have a media listing api so that avni-media can show them on the screen

PS: Please talk to Vinay when picking up this story

### API Details
- API /media?size=x&page=y to retrieve the following values
```
[
    {
      uuid: "" (from the media table)
      url: 
      subjectName: <subjectName>
      subjectTypeName: <subjectTypeName>
      programEnrolment: <programName> 
      encounterTypeName: <encounterTypeName>
      lastModifiedDateTime: <lastModifiedDateTime> 
      createdDateTime: <createdDateTime>
      syncConcept1Name: <Sync Concept 1 for this subject type> 
      syncConcept2Name:  <Sync Concept 2 for this subject type> 
      syncParameterValue1
      syncParameterValue2
      address: {
        District: "abc",
        Block: "abc",
       }
    }
]
```
- Auth based on value in cookie or auth-token. App will identify organisation/schema based on this
- Will be sorted by createdDateTime desc so that latest pictures show up first
- We will eventually also build a filter functionality here
- Pagination will be required

**Comment by vinayvenu** [comment]
2 + 2

**Comment by petmongrels** [comment]
There is no need to pass org id in the http requests because the organisation should be figured out from the token on the server.

**Comment by rudresh** [comment]
@petmongrels The use of org Id is temporary. I agree that the org id should be fetched form the token. We have a card for using token for authentication. I have added the replacement of org Id in the same [card](https://app.zenhub.com/workspaces/avni-product-635b73bded85e50018871ae6/issues/gh/avniproject/avni-webapp/943)

**Comment by petmongrels** [comment]
- we should use material ui and react components instead of generating HTML by hand. Material UI handles many styling issues and it is much lesser code to maintain. This code will be very difficult to maintain in future.
- what is the reason for using localStorage instead of react state management mechanisms. there are very few things 
- no unit test for getFileSizeText method (this method should be moved to domain layer ideally)
