### ISSUE TITLE
Run ETL through API

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#49]
### Story
Earlier, we were able to run ETL for an organisation. However, now that it is running as a service, we are not able to run ETL for an organisation, and need to wait an hour each time (unless we restart the service). As part of this story, we will enable ETL for an organisation

### Acceptance criteria
- POST /job?schema="abc" with admin role required
- Job should not interfere with existing jobs
- GET /job/status?schema="abc" to get status of jobs for schema "abc" - gives start time, status

**Comment by 1t5j0y** [comment]
New APIs not required since the existing API to enable and disable analytics can serve this purpose. Will close this card after adding documentation around this.

**Comment by 1t5j0y** [comment]
Updated documentation - https://avni.readme.io/docs/recreate-etl-schema-for-an-implementation#new-webapp-based-method
