### ISSUE TITLE
Support group subjects in ETL schema

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#50]
### Reason
Typically, group_subject table is just an m-n relationship table which is usually searched by a specific foreign key. However, when it comes to households, retrieving "head of household" is a common need. Having a separate table for each group type helps improve both performance as well as adds simplicity to the queries (if we add a head of household as a direct column). 

### Schema description
- table named groupSubject_memberSubject
- If group subject is of type household, then head_of_household_id is additionally added to the table schema

### Testing notes
- Handle Addition / Removal of Members from a group
- Change of head of household must be handled correctly (Head  of Household becomes common member and the other way around)
- ~Optional: Include "Head of Household name" in table and handle its update when there is change in role of member from Head to regular and vice-versa.~ Not including "Head of Household name", to avoid mismatch in names across source and GroupSubject table.

**Comment by himeshr** [comment]
Code changes in etl (main) branch and avni-server(master) branch.
Testing done using Yenepoya org. Attached sample Yenepoya org GroupSubject table.

[yenepoya_household_individual.csv](https://github.com/avniproject/avni-etl/files/11905550/yenepoya_household_individual.csv)
