### ISSUE TITLE
Authentication for ETL Service

### ISSUE THREAD

**Issue by petmongrels** [avniproject/avni-etl#53]
Currently one can access endpoints without providing any token. The media endpoint is perhaps protected but it should be generically implemented.

**Comment by petmongrels** [comment]
- We can leave out Account, AccountAdmin
- org.avniproject.etl.domain.OrgIdentityContextHolder#startTime should also be in ThreadLocal (or else we will forget to fix it when we switch config to multi-threaded in future)

**Comment by 1t5j0y** [comment]
Made code changes after last review to get auth working end to end from the webapp. Moving back to Code Review Ready.
Changes:
ETL: https://github.com/avniproject/avni-etl/compare/f15cc033578b6b4568f2b2a78b1160fba9e8b096...1b34234398ea46d70526b6ee4f1eea75da6c43f4
Webapp: https://github.com/avniproject/avni-webapp/compare/8fcde6db83d9aa781c20b4ea4cf73f88891125b0...bfa69d9561b35e45f52123f24ec157b22af07f8f
Infra: https://github.com/avniproject/avni-infra/commit/003f0b0a010e3386bdb4daa95a89a0519ed8ee79
