### ISSUE TITLE
ETL documentation

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#58]
With the new changes in ETL, it is important to document on readme

1. How to stop/start the service
2. How to run for a particular organisation
3. How to enable ETL for an organisation
4. How to see which organisations have ETL enabled
5. Anything else that is relevant

**Comment by petmongrels** [comment]
https://avni.readme.io/docs/etl-schema-and-reporting#management-of-etl-process-for-an-organisation

https://avni.readme.io/docs/developer-environment-setup-ubuntu#avni-etl-server
