### ISSUE TITLE
Update the cancel_date_time in the ETL encounter table

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-etl#64]
Currently, ETL generates a table for each encounter type and has the cancel_date_time column as well, but when an encounter is cancelled, ETL updates that entry in the encounter's cancel table separately. But ideally it should have been done in any of the following ways, in order to avoid confusions to the developers -

1. Either the cancel_date_time and the last_modified details should get updated in the encounter table as well
2. Or the cancel_date_time column shouldn't be part of the encounter table in ETL.

On of the above options should be considered and implemented so that devs have clear approach when handling cancel scenarios in the reports logic.

**Comment by vinayvenu** [comment]
Cancelling on account of https://github.com/avniproject/avni-etl/issues/95
