### ISSUE TITLE
Remove usage of is_org_admin from ETL controllers

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#65]
is_org_admin has been deprecated but ETL still refers to it. This is causing 403 errors for all in the media viewer for regular users who do not have the is_org_admin turned on.

**Comment by petmongrels** [comment]
prepared statements here
https://github.com/avniproject/avni-etl/commit/90129fd7dd2e9f6c3e7cc65eef0d1ab8d32dd12b#diff-a0d24637e7aa38ed0b36daf08384423b991942fe81fcc6bb1bd9f551c629a0bdR17
