### ISSUE TITLE
Media Viewer does not show for users with Analytics access

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#69]

**Comment by AchalaBelokar** [comment]
I deploy the server and disable the toggle button still media and report box is showing

**Comment by petmongrels** [comment]
On disabling.
- media viewer box is not shown
- report box is shown but user cannot run any reports
(as expected)

Cannot reproduce the issue.
- Need login details

**Comment by ashusvnath** [comment]
Issue not reproducible with image issue organization (AchalaB@im, nonadmin@im)
