### ISSUE TITLE
Healthcheck for ETL Service for Poweratuat

### ISSUE THREAD

**Issue by Dinesh2019** [avniproject/avni-etl#70]
For the account poweratuat we can able to see the data synced at 11.37 after that no job is ran for this org

Org : Poweratuat
user : dinesh@poweratuat

<img width="1710" alt="Screenshot 2023-09-12 at 3 15 30 PM" src="https://github.com/avniproject/avni-etl/assets/127730126/29a338d1-641e-4ec5-befa-524b9bd5d03b">

**Comment by vinayvenu** [comment]
@petmongrels is this what you are working on?

**Comment by petmongrels** [comment]
yes, I have created freshping entry to uptime of etl service

**Comment by vinayvenu** [comment]
nice. closing this.
