### ISSUE TITLE
Duplicate rows in the ETL tables

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-etl#73]
Issue:
For group org rwb_org_2023 sometimes ETL generates duplicate entries in all tables.

Earlier we fixed this issue by deleting the org-specific schema and regenerating the ETL for Group Org only.

For Media Viewer, ETL need to be enabled at individual org level, and for reports ETL  is enabled at group org level.
When ETL is enabled at both levels, group org schema in ETL has duplicate rows.

**Comment by vinayvenu** [comment]
Real code change only to the delete_etl_metadata_for_* procedures, which can cause trouble
