### ISSUE TITLE
Cancel table not in sync with base table for UnCancel scenario

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/avni-etl#75]
https://avni.freshdesk.com/a/tickets/3163

There are scenarios where an encounter is cancelled by one user and filled in by another user. If the first user syncs, ETL creates a row in the _cancel table. When the second user syncs, the program_encounter row is overwritten, but the row in the _cancel table is not deleted. 

### Acceptance criteria
- When a cancelled encounter is uncancelled on the program_encounter or the encounter table, the corresponding row on the _cancel table is deleted.

**Comment by dinesh2096** [comment]
- [ ] The cancel table is not updated as per the requirement.

env : staging 
org : dinesh@dashsix
Individual :  Test din oct0101


Refer image : 

encounter table : 

![Image](https://github.com/user-attachments/assets/f0988d01-9be4-4ecc-bce9-1c2ab88f70aa)

Cancel Table : 

![Image](https://github.com/user-attachments/assets/22197d9f-734e-44cb-b6a5-0d6c4b676324)

**Comment by 1t5j0y** [comment]
Fix was not deployed to staging. I have triggered deployment to staging now. Please retest.

**Comment by dinesh2096** [comment]
QA References : 

[Click here to watch video](https://drive.google.com/file/d/1BponPK_memcjGDoL7SBBDdD4a0-FsUwN/view?usp=drive_link)

**Comment by 1t5j0y** [comment]
Fix is at ETL level and not dependent on source of data so testing from client should be sufficient.
