### ISSUE TITLE
Unable to view some media types on Media Viewer

### ISSUE THREAD

**Issue by sachsk** [avniproject/avni-etl#79]
## Context
When we are uploading the files using the "File" dataType concept those files are not available on the Media viewer.

## Acceptance criteria

- When user uploads the file/audio from the app then it should be available for download in the media viewer.
- ~~Rename image_url column in media table to media_url~~

## Analysis: 

```findColumnsMatchingConceptType``` in ```MediaTableSyncAction``` considers only Image and Video

**Comment by mahalakshme** [comment]
@1t5j0y this is not done: Rename image_url column in media table to media_url
Can you also please attach a screenshot/video of the media page(with whatever u ve already tested - need not be perfect) here(with file and video/audio thumbnails) - will help for release sign-off showcase, product showcase, else need to spend time to setup.

**Comment by 1t5j0y** [comment]
@mahalakshme sure, will do. Hope there are no existing queries in reports etc that expect the column name to be `image_url`.

**Comment by mahalakshme** [comment]
@1t5j0y good point, since this is a new table I dont think so, but will confirm once.

**Comment by mahalakshme** [comment]
@1t5j0y we can assume it is not used in the reports, since I didnt receive any concerns over modifying this from the other team.

**Comment by 1t5j0y** [comment]
Screenshot of media viewer with this change:

Audio / Video types use the same 'play button' icon.
File has a different icon.
Images continue to show the actual image.

![Image](https://github.com/avniproject/avni-etl/assets/54208632/fe54afe5-961c-4bd5-8c81-96200aa114ed)

**Comment by AchalaBelokar** [comment]
I tried to download the audio file Not able to download
