### ISSUE TITLE
Need enrolment ID in Program Exit and Program Encounters

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/avni-etl#86]
Within reports, implementors come across a lot of scenarios where an individual is enrolled to same program multiple times. And while writing a report around program encounter & exit details it is not clear how to map it to the right/corresponding program enrolment.

One work around for example we used recently is - 

Instead of -

`LEFT JOIN individual_mother_exit on individual_mother_exit.individual_id = enl.individual_id 
`
we replaced it with and extra condition

`LEFT JOIN individual_mother_exit on individual_mother_exit.individual_id = enl.individual_id and enl.enrolment_date_time = individual_mother_exit.enrolment_date_time
`        

This is quite difficult for (external/internal) implementors to understand, hence we need a clear enrolment ID in the respective program encounter & exit tables.

**Comment by vinayvenu** [comment]
@nupoorkhandelwal it looks like what you need already exists in the tables. 

In program_exit tables, the id column is the enrolment id
In program_encounter tables, program_enrolment_id is already present

Closing this card. Reopen if you feel you see any issues.
