### ISSUE TITLE
Voided data for user table not available in org ETL schemas

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-etl#94]
https://avni.freshdesk.com/a/tickets/3665

The user table in the org ETL schemas contains the `is_voided` column but has null values for all rows.

Appears to be a simple fix to include `is_voided` in `user.sql.st`

### AC:
The values for the  `is_voided` column in the org ETL schema `user` table should be populated correctly.

**Comment by vinayvenu** [comment]
is_voided is present in the users table, but cannot be modified by any of the interfaces provided in Avni today. Not sure why this was picked up. 

Verified by manually voiding user from the database.
